### ISSUE TITLE
function to read in terrestrial data 

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwgtools#18]
sheet name is `bromeliad.terrestrial`
data to be used by @DEZERALDOlivier

**Comment by DEZERALDOlivier** [comment]
there is no sheet called "bromeliad.terrestrial" when I use combine_tab??

**Comment by aammd** [comment]
@DEZERALDOlivier were you getting errors like this?

```r
Error in match.arg(sheetname, c("leaf.waterdepths", "bromeliad.physical",  : 
  'arg' should be one of “leaf.waterdepths”, “bromeliad.physical”, “bromeliad.final.inverts”, “site.info”, “site.weather”, “bromeliad.initial.inverts”
```

Because I had a similar issue when i checked!  I fixed it by reinstalling the package. 
try running `devtools::install_github()` again and see if it works!

**Comment by DEZERALDOlivier** [comment]
right and still not working despite reinstalling the package!!!

**Comment by DEZERALDOlivier** [comment]
another thing, R cannot find the function: site.info_read()

**Comment by DEZERALDOlivier** [comment]
when I try: devtools::install_github() it says Error in lapply(repo,.......) argument repo is missing, with no default

**Comment by DEZERALDOlivier** [comment]
Ok final comment but not least, I am actually playing around with the bwgtools and I see several ways to improve the use of this package. I put myself in the place of someone who wants to use it for analyses and my first impression is: where could I find the information I need? You have done such an amazing job at compiling all this information so I think the content is there but it lacks structure and simplicity. We could discuss this sometime, let me know!

**Comment by aammd** [comment]
uh-oh! these are problems that I want to be very careful about. 
Would you please restart R (start with an empty workspace) and repeat the entire process of downloading, loading and running the package:

```r
library(devtools)
install_github("Srivastavalab/bwgtools")
library(bwgtools)
terr <- combine_tab(c("Cardoso", "French_Guiana", "Colombia",
                      "Macae", "PuertoRico","CostaRica"),
                    sheetname = "bromeliad.terrestrial")
```

Then, if there is still an error, would you please run `sessionInfo()` and send me the result? You can either paste it here or email me, as you like

**Comment by aammd** [comment]
re: documentation, let us make a separate issue for just that.

**Comment by aammd** [comment]
:rocket: M @DEZERALDOlivier,  nous avons encore un problème?

**Comment by DEZERALDOlivier** [comment]
Hi Andrew,

I am confused it is stil not working could we skype again sometime?

**Comment by aammd** [comment]
zut alors! yes, are you free today

**Comment by DEZERALDOlivier** [comment]
yes whenever you want!

**Comment by DEZERALDOlivier** [comment]
sessionInfo()

R version 3.1.2 (2014-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)

locale:
[1] LC_COLLATE=French_France.1252 
[2] LC_CTYPE=French_France.1252   
[3] LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                  
[5] LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

other attached packages:
[1] knitr_1.10.5   dplyr_0.4.1    readxl_0.1.0  
[4] rdrop2_0.6     bwgtools_0.1   devtools_1.8.0

loaded via a namespace (and not attached):
 [1] assertthat_0.1    bitops_1.0-6      DBI_0.3.1        
 [4] digest_0.6.8      git2r_0.10.1      httr_0.6.1       
 [7] jsonlite_0.9.16   lazyeval_0.1.10   magrittr_1.5     
[10] memoise_0.2.1     parallel_3.1.2    R6_2.0.1         
[13] Rcpp_0.11.6       RCurl_1.95-4.6    rstudio_0.98.1091
[16] rstudioapi_0.3.1  rversions_1.0.0   stringi_0.4-1    
[19] stringr_1.0.0     tools_3.1.2       XML_3.98-1.1
