### ISSUE TITLE
Improve the documentation

### ISSUE THREAD

**Issue by aammd** [SrivastavaLab/bwgtools#19]
Right now, `bwgtools` is a tool that only Andrew can use (in its entirety), when actually it is a tool for **everyone**! The package should be accompanied by clear documentation. The first priority is clear communication with all members of the BWG research group. The second is communication with reviewers, editors and readers of the manuscripts we produce.

I would like this issue to be a place to hold all the discussion we have on this topic. We can open separate ones for specific tasks once they arise.

I really encourage everyone who is using this package to consider contributing to documentation! I will help settle any doubts you might have about exactly how to do it (e.g. if you want to edit the documentation of a function).

here are some things I think could be better:

* Function names -- many functions are named different things, even though they are related. For example, functions which download data are called `read_sheet`, `read_site_sheet`, `get_all_sites` and `combine_tab`. Should they all be renamed to `download_x`, where `x` is something specific?
* Function documentation -- there is minimal documentation, but lots could be improved there. Examples would be great, plus an expanded "details" section
* README -- is OK, but could have more developed sections. 
    * Accessing data
    * Combining data
    * Calculations
    * Analyses (when we have those)
    * Plots
* Translations -- Should we have a French/Spanish/Portuguese translation of the README? Of any part of this? Would anyone like that?

**Comment by aammd** [comment]
I know that @nacmarino  and @DEZERALDOlivier have had many helpful observations on the documentation and organization so far; please feel free to contribute your thoughts here

**Comment by nacmarino** [comment]
Yes!

I agree with you...I was having some difficulties to try and find which functions do what. In fact, I was going to ask you before I left if you wanted me to do it.

I could do it and work with you. Also, I believe that a translation of the documentation should not be a priority now - but we should think about it once the package is working nicely.

I think, you suggestion of the 'download_x' is very nice. This is very intuitive.

**Comment by dsrivast** [comment]
Hi Andrew- This is looking great, thank you. A few suggestions. Lets call them "rainfall metrics" not "hydrology based on rainfall"...that's too confusing. Hydrology will refer just to the bromeliad water depths. My other suggestion is to move the definitions of the hydrology variables (currently in its own file, easily overlooked) into this document. So its clear what they are (like what you did for the functional groups, but more so). Do we need to strike a small group to come up with rainfall metrics? @nacmarino @aammd

**Comment by nacmarino** [comment]
I thought we already had the rainfall metrics.

If not, I have the code here and can put it in the gituhub folder.

**Comment by DEZERALDOlivier** [comment]
Hi all, 
We now have a skeleton of the package documentation, type in: ?"bwgtools" in R you'll see the documentation for the package as a whole! I followed your advices @aammd: Accessing, Combining, Calculating, and Analyzing. We'll see later for the plot section. Each section has an example of available functions. It is now a little bit more intuitive than the raw list of all functions, which I have been through all of them and some are not working on my computer (we can discuss this later). We can now fill in each section, for instance, in "Calculating metrics" there will be two subsections: Hydrological metrics (related to water depths) and Rainfall metrics (related to rainfall distribution). Tell me what you think?

**Comment by DEZERALDOlivier** [comment]
Thinking about it we could add an "Info" section, that would get general information from all sites (site descriptions, precipitations, bromeliad species etc..). In the same way as get_bwg_names()?!

**Comment by aammd** [comment]
I want to close this.. @DEZERALDOlivier do you want this "info" section you were talking about? perhaps open another issue for this?
