### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by adletaw** [SrivastavaLab/bwgtools#21]
May I push a .gitattributes file to keep linux line endings?

**Comment by aammd** [comment]
@adletaw did you actually do this? because YES PLEASE

**Comment by adletaw** [comment]
Yes, I started to but never uploaded it because I didn't want to mess up 
your work.  I'll refresh my version and get it set up.

On 8/20/2015 4:49 PM, Andrew MacDonald wrote:
>
> @adletaw <https://github.com/adletaw> did you actually do this? 
> because YES PLEASE
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwgtools/issues/21#issuecomment-133213761>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Comment by adletaw** [comment]
.gitattributes file [added](https://github.com/SrivastavaLab/bwgtools/blob/master/.gitattributes)
