### ISSUE TITLE
read_site_sheet() vs. combine_tab()

### ISSUE THREAD

**Issue by DEZERALDOlivier** [SrivastavaLab/bwgtools#22]
Arg <- read_site_sheet("Argentina","leaf.waterdepths")
Arg1 <- combine_tab("Argentina","leaf.waterdepths")

firstday(Arg) => it works fine!
firstday(Arg1) => it doesn't work! when you call for combine_tab(): "bromeliad.id" column is not found in the sheetname=leaf.waterdepths

the question is why they call for different columns even though it's the same sheetname? 
This the same issue with the function: from_start()!

**Comment by aammd** [comment]
yeah, this function was never really intended for public use! part of an internal process for generating a complete time series for each block. So I've taken it away :smile_cat: If you'd like it back please give me an example of how and where it ought to be used.
